icons_format = "{icon}"

[theme]
theme = "ctp-latte"
#theme = "native"

[icons]
icons = "awesome6"

[[block]]
block = "packages"
package_manager = ["pacman", "aur"]
interval = 600
error_interval = 300
format = "   Pacman:$pacman # Aur:$aur "
format_singular = "   $total update available "
format_up_to_date = "   system up to date "
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"

[[block]]
block = "nvidia_gpu"
interval = 1
format = " ^icon_gpu $name $utilization $fan_speed "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $ip }{ ^icon_net_down $graph_down ^icon_net_up $graph_up }"

[[block]]
block = "temperature"

[[block]]
block = "load"
interval = 1  
[[block]]
block = "cpu"
interval = 1
 
[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi) / $mem_avail.eng(prefix:Mi) ($mem_used_percents.eng(w:2))"
interval = 10
warning_mem = 70
critical_mem = 90 

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total " 
[[block.click]]
button = "right"
update = true


[[block]]
block = "battery"
driver = "sysfs"
format = " $icon $percentage "
 
[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%A %Y-%m-%d %R:%S')"

[[block]]
block = "sound"

[[block]]
block = "backlight"
